defmodule Docpub.Markdown do
  @moduledoc """
  Renders markdown content to HTML using mdex.
  Handles wiki-link resolution, image path rewriting, and Mermaid code block preservation.
  """

  @doc """
  Renders a markdown string to safe HTML.

  Options:
    - `:file_tree` - flat list of `%Vault{}` nodes for wiki-link resolution
    - `:current_dir` - directory of the current document (for relative image resolution)
    - `:vault_path` - the vault base path (for image URL generation)
  """
  @spec render(String.t(), keyword()) :: {:ok, String.t()} | {:error, term()}
  def render(markdown, opts \\ []) do
    file_tree = Keyword.get(opts, :file_tree, [])
    current_dir = Keyword.get(opts, :current_dir, "")

    case MDEx.to_html(markdown,
           extension: [
             wikilinks_title_after_pipe: true,
             strikethrough: true,
             table: true,
             autolink: true,
             tasklist: true,
             footnotes: true
           ],
           parse: [
             smart: true
           ],
           render: [
             unsafe_: true
           ]
         ) do
      {:ok, html} ->
        html =
          html
          |> rewrite_wikilinks(file_tree)
          |> rewrite_obsidian_images(current_dir)
          |> rewrite_standard_images(current_dir)
          |> preserve_mermaid_blocks()

        {:ok, html}

      {:error, reason} ->
        {:error, reason}
    end
  end

  # Rewrite wiki-link anchors generated by mdex.
  # mdex outputs: <a href="target" data-wikilink="true">display</a>
  defp rewrite_wikilinks(html, file_tree) do
    Regex.replace(
      ~r/<a href="([^"]*)" data-wikilink="true">([^<]*)<\/a>/,
      html,
      fn _full, target, display ->
        case resolve_wikilink(target, file_tree) do
          {:ok, path} ->
            ~s(<a href="/doc/#{encode_path(path)}" class="vault-link">#{display}</a>)

          :not_found ->
            ~s(<span class="vault-link-broken" title="Page not found: #{target}">#{display}</span>)
        end
      end
    )
  end

  defp resolve_wikilink(target, file_tree) do
    target_down = String.downcase(target)

    match =
      Enum.find(file_tree, fn node ->
        name_no_ext = node.name |> Path.rootname() |> String.downcase()
        path_no_ext = node.path |> Path.rootname() |> String.downcase()

        name_no_ext == target_down or
          path_no_ext == target_down or
          String.downcase(node.path) == target_down
      end)

    case match do
      nil -> :not_found
      node -> {:ok, strip_md_extension(node.path)}
    end
  end

  defp strip_md_extension(path) do
    if Path.extname(path) in ~w(.md .markdown) do
      Path.rootname(path)
    else
      path
    end
  end

  # Rewrite Obsidian-style image embeds: ![[image.png]]
  # These appear as literal text in the HTML since mdex doesn't parse them
  defp rewrite_obsidian_images(html, current_dir) do
    Regex.replace(~r/!\[\[([^\]]+)\]\]/, html, fn _full, image_path ->
      resolved = resolve_image_path(image_path, current_dir)

      ~s(<img src="/vault_file/#{encode_path(resolved)}" alt="#{image_path}" class="vault-image" />)
    end)
  end

  # Rewrite standard markdown image paths to point to vault file serving route
  defp rewrite_standard_images(html, current_dir) do
    Regex.replace(
      ~r/<img([^>]*) src="(?!https?:\/\/|\/vault_file\/)([^"]*)"([^>]*)>/,
      html,
      fn _full, pre, src, post ->
        resolved = resolve_image_path(src, current_dir)
        ~s(<img#{pre} src="/vault_file/#{encode_path(resolved)}"#{post}>)
      end
    )
  end

  defp encode_path(path) do
    path
    |> String.split("/")
    |> Enum.map_join("/", fn segment -> URI.encode(segment, &URI.char_unreserved?/1) end)
  end

  defp resolve_image_path(image_path, current_dir) do
    if current_dir == "" do
      image_path
    else
      Path.join(current_dir, image_path)
    end
  end

  # Replace syntax-highlighted mermaid code blocks with plain ones for client-side rendering.
  # mdex wraps them in <pre class="lumis" ...><code class="language-mermaid" ...>
  defp preserve_mermaid_blocks(html) do
    Regex.replace(
      ~r/<pre[^>]*><code[^>]*class="language-mermaid"[^>]*>(.*?)<\/code><\/pre>/s,
      html,
      fn _full, content ->
        # Strip the lumis line divs and decode entities
        clean =
          content
          |> String.replace(~r/<div[^>]*>/, "")
          |> String.replace("</div>", "")
          |> String.replace("&amp;", "&")
          |> String.replace("&lt;", "<")
          |> String.replace("&gt;", ">")
          |> String.replace("&quot;", "\"")
          |> String.trim()

        ~s(<pre class="mermaid">#{clean}</pre>)
      end
    )
  end
end
