defmodule Docpub.Markdown do
  @moduledoc """
  Renders markdown content to HTML using mdex.
  Handles wiki-link resolution, image path rewriting, and Mermaid code block preservation.
  """

  alias Docpub.WhatsNew.Hunk

  @doc """
  Renders a markdown string to safe HTML.

  Options:
    - `:file_tree` - flat list of `%Vault{}` nodes for wiki-link resolution
    - `:current_dir` - directory of the current document (for relative image resolution)
    - `:vault_path` - the vault base path (for image URL generation)
    - `:line_marks` - list of `%Docpub.WhatsNew.Hunk{}` to stamp `data-whats-new`
      attributes onto top-level blocks whose source lines overlap a hunk.
  """
  @spec render(String.t(), keyword()) :: {:ok, String.t()} | {:error, term()}
  def render(markdown, opts \\ []) do
    file_tree = Keyword.get(opts, :file_tree, [])
    current_dir = Keyword.get(opts, :current_dir, "")
    line_marks = Keyword.get(opts, :line_marks, [])
    sourcepos? = line_marks != []

    case MDEx.to_html(markdown,
           extension: [
             wikilinks_title_after_pipe: true,
             strikethrough: true,
             table: true,
             autolink: true,
             tasklist: true,
             footnotes: true
           ],
           parse: [
             smart: true
           ],
           render: [
             unsafe_: true,
             sourcepos: sourcepos?
           ]
         ) do
      {:ok, html} ->
        html =
          html
          |> rewrite_wikilinks(file_tree)
          |> rewrite_obsidian_images(current_dir)
          |> rewrite_standard_images(current_dir)
          |> preserve_mermaid_blocks()
          |> apply_line_marks(line_marks)

        {:ok, html}

      {:error, reason} ->
        {:error, reason}
    end
  end

  # Walks the top-level blocks of the rendered HTML and stamps `data-whats-new`
  # plus `aria-label` on any block whose source line range overlaps one of the
  # supplied hunks. No-op when `hunks` is empty.
  defp apply_line_marks(html, []), do: html

  defp apply_line_marks(html, hunks) do
    doc = LazyHTML.from_fragment(html)

    new_tree =
      doc
      |> LazyHTML.to_tree()
      |> Enum.map(&stamp_node(&1, hunks))

    new_tree
    |> LazyHTML.from_tree()
    |> LazyHTML.to_html()
  end

  defp stamp_node({tag, attrs, children}, hunks) do
    case List.keyfind(attrs, "data-sourcepos", 0) do
      {"data-sourcepos", value} ->
        case overlap_kind(value, hunks) do
          nil ->
            {tag, drop_sourcepos(attrs), children}

          kind ->
            label =
              case kind do
                :added -> "Added since your last visit"
                :modified -> "Updated since your last visit"
              end

            attrs =
              attrs
              |> drop_sourcepos()
              |> List.keystore("data-whats-new", 0, {"data-whats-new", Atom.to_string(kind)})
              |> List.keystore("aria-label", 0, {"aria-label", label})

            {tag, attrs, children}
        end

      _ ->
        {tag, attrs, children}
    end
  end

  defp stamp_node(other, _hunks), do: other

  defp drop_sourcepos(attrs), do: List.keydelete(attrs, "data-sourcepos", 0)

  # `data-sourcepos` looks like "line:col-line:col". `:added` wins over
  # `:modified` when both kinds overlap.
  defp overlap_kind(sourcepos, hunks) do
    case parse_sourcepos(sourcepos) do
      nil ->
        nil

      {start_line, end_line} ->
        Enum.reduce(hunks, nil, fn %Hunk{} = h, acc ->
          if ranges_overlap?(start_line, end_line, h.start_line, h.end_line) do
            promote(acc, h.kind)
          else
            acc
          end
        end)
    end
  end

  defp parse_sourcepos(value) do
    case Regex.run(~r/^(\d+):\d+-(\d+):\d+$/, value) do
      [_, s, e] -> {String.to_integer(s), String.to_integer(e)}
      _ -> nil
    end
  end

  defp ranges_overlap?(a1, a2, b1, b2), do: a1 <= b2 and b1 <= a2

  defp promote(:added, _), do: :added
  defp promote(_, :added), do: :added
  defp promote(nil, kind), do: kind
  defp promote(kind, _), do: kind

  # Rewrite wiki-link anchors generated by mdex.
  # mdex outputs: <a href="target" data-wikilink="true">display</a>
  defp rewrite_wikilinks(html, file_tree) do
    Regex.replace(
      ~r/<a href="([^"]*)" data-wikilink="true">([^<]*)<\/a>/,
      html,
      fn _full, target, display ->
        case resolve_wikilink(target, file_tree) do
          {:ok, path} ->
            ~s(<a href="/doc/#{encode_path(path)}" class="vault-link">#{display}</a>)

          :not_found ->
            ~s(<span class="vault-link-broken" title="Page not found: #{target}">#{display}</span>)
        end
      end
    )
  end

  defp resolve_wikilink(target, file_tree) do
    target_down = String.downcase(target)

    match =
      Enum.find(file_tree, fn node ->
        name_no_ext = node.name |> Path.rootname() |> String.downcase()
        path_no_ext = node.path |> Path.rootname() |> String.downcase()

        name_no_ext == target_down or
          path_no_ext == target_down or
          String.downcase(node.path) == target_down
      end)

    case match do
      nil -> :not_found
      node -> {:ok, strip_md_extension(node.path)}
    end
  end

  defp strip_md_extension(path) do
    if Path.extname(path) in ~w(.md .markdown) do
      Path.rootname(path)
    else
      path
    end
  end

  # Rewrite Obsidian-style image embeds: ![[image.png]]
  # These appear as literal text in the HTML since mdex doesn't parse them
  defp rewrite_obsidian_images(html, current_dir) do
    Regex.replace(~r/!\[\[([^\]]+)\]\]/, html, fn _full, image_path ->
      resolved = resolve_image_path(image_path, current_dir)

      ~s(<img src="/vault_file/#{encode_path(resolved)}" alt="#{image_path}" class="vault-image" />)
    end)
  end

  # Rewrite standard markdown image paths to point to vault file serving route
  defp rewrite_standard_images(html, current_dir) do
    Regex.replace(
      ~r/<img([^>]*) src="(?!https?:\/\/|\/vault_file\/)([^"]*)"([^>]*)>/,
      html,
      fn _full, pre, src, post ->
        resolved = resolve_image_path(src, current_dir)
        ~s(<img#{pre} src="/vault_file/#{encode_path(resolved)}"#{post}>)
      end
    )
  end

  defp encode_path(path) do
    path
    |> String.split("/")
    |> Enum.map_join("/", fn segment -> URI.encode(segment, &URI.char_unreserved?/1) end)
  end

  defp resolve_image_path(image_path, current_dir) do
    if current_dir == "" do
      image_path
    else
      Path.join(current_dir, image_path)
    end
  end

  # Replace syntax-highlighted mermaid code blocks with plain ones for client-side rendering.
  # mdex wraps them in <pre class="lumis" ...><code class="language-mermaid" ...>
  defp preserve_mermaid_blocks(html) do
    Regex.replace(
      ~r/<pre[^>]*><code[^>]*class="language-mermaid"[^>]*>(.*?)<\/code><\/pre>/s,
      html,
      fn _full, content ->
        # Strip the lumis line divs and decode entities
        clean =
          content
          |> String.replace(~r/<div[^>]*>/, "")
          |> String.replace("</div>", "")
          |> String.replace("&amp;", "&")
          |> String.replace("&lt;", "<")
          |> String.replace("&gt;", ">")
          |> String.replace("&quot;", "\"")
          |> String.trim()

        ~s(<pre class="mermaid">#{clean}</pre>)
      end
    )
  end
end
